(DEFUN MERGESORT (NLIST1 NLIST2)
  (COND ((NULL NLIST1)
	 (COND ((NULL NLIST2) NIL)
	       (T (CONS (CAR NLIST2) (MERGESORT NLIST1 (CDR NLIST2))))))
	(T
	 (COND ((NULL NLIST2) (CONS (CAR NLIST1) (MERGESORT (CDR NLIST1) NLIST2)))
	       (T (COND ((< (CAR NLIST1) (CAR NLIST2))
			 (CONS (CAR NLIST1) (MERGESORT (CDR NLIST1) NLIST2)))
			(T (CONS (CAR NLIST2) (MERGESORT NLIST1 (CDR NLIST2))))))))))
