(DEFUN ALTMERGE (L1 L2)
  (COND ((NULL L1)
	 (COND ((NULL L2) NIL)
	       (T (CONS (CAR L2) (ALTMERGE L1 (CDR L2))))))
	(T
	 (COND ((NULL L2) (CONS (CAR L1) (ALTMERGE (CDR L1) L2)))
	       (T (APPEND (LIST (CAR L1) (CAR L2)) (ALTMERGE (CDR L1) (CDR L2))))))))
