answs = {
1 : {'A' : 'not linux based',
      'B' : '7 or less',
      'C' : 'web',
      'D' : 'yes'},
2 : {'A' : 'linux based',
     'B' : '7 or less',
     'C' : 'app',
     'D' : 'yes'},
3 : {'A' : 'linux based',
     'B' : '7 or less',
     'C' : 'both',
     'D' : 'yes'},
4 : {'A' : 'linux based',
     'B' : '7 or less',
     'C' : 'both',
     'D' : 'yes'},
5 : {'A' : 'not linux based',
     'B' : '7 or less',
     'C' : 'web',
     'D' : 'yes'},
6 : {'A' : 'linux based',
     'B' : '7 or less',
     'C' : 'app',
     'D' : 'no'},
7 : {'A' : 'linux based',
     'B' : '7 or less',
     'C' : 'app',
     'D' : 'yes'},
8 : {'A' : 'linux based',
     'B' : 'over 7',
     'C' : 'web',
     'D' : 'yes'},
9 : {'A' : 'not linux based',
     'B' : '7 or less',
     'C' : 'both',
     'D' : 'no'},
10 : {'A' : 'linux based',
      'B' : 'over 7',
      'C' : 'app',
      'D' : 'yes'},
11 : {'A' : 'linux based',
      'B' : 'over 7',
      'C' : 'both',
      'D' : 'no'},
12 : {'A' : 'linux based',
      'B' : 'over 7',
      'C' : 'both',
      'D' : 'yes'},
13 : {'A' : 'not linux based',
      'B' : '7 or less',
      'C' : 'web',
      'D' : 'no'},
14 : {'A' : 'linux based',
      'B' : '7 or less',
      'C' : 'web',
      'D' : 'yes'},
15 : {'A' : 'linux based',
      'B' : '7 or less',
      'C' : 'both',
      'D' : 'yes'},
16 : {'A' : 'not linux based',
      'B' : '7 or less',
      'C' : 'both',
      'D' : 'no'}
}
